language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - rbx
  - jruby-1.7.20

sudo: false

branches:
  only:
    - master

gemfile:
  - Gemfile

script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-1.7.20

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
